- name: Change Vault default address from https to http 
  lineinfile:
    line: export VAULT_ADDR='http://127.0.0.1:8200'
    path: /home/vagrant/.bashrc

- name: Install vault 
  package:
    name: vault 
    state: present 

- name: Copy vault config file 
  copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: Enable and start vault server 
  service:
    name: vault 
    state: started
    enabled: true