Vagrant.configure("2") do |config|
  config.vm.box = "bento/almalinux-9"
  config.vm.hostname = "alma-linux-9"
  config.vm.box_version = "202206.14.0"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.90.150"
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "alma-linux-9"
    vb.cpus   = 2
    vb.memory = "4096"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "localstack.yml"
    ansible.become   = true
  end
end
