Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"
  config.vm.hostname = "ubuntu"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.85.133"
  config.vm.provider "vmware_fusion" do |vf|
    vf.memory = 2048
    vf.cpus = 2
    vf.vmx["ethernet0.virtualdev"] = "vmxnet3"
  end
end