Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "ubuntu"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.80.100"
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "ubuntu"
    vb.cpus   = 2
    vb.memory = "4096"
  end
end
  